export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const TOGGLE_EMPLOYEE = 'TOGGLE_EMPLOYEE';
export const REMOVE_EMPLOYEE = 'REMOVE_EMPLOYEE';
export const REMOVE_ALL_EMPLOYEE = 'REMOVE_ALL_EMPLOYEE';
